import { createAction } from "@reduxjs/toolkit";
import { divisionActionTypes as actions } from '../action-types/division';


//Crear Quizz
const CREATE_DIVISION_REQUESTED_ACTION = createAction(actions.CREATE_DIVISION_REQUESTED);
const CREATE_DIVISION_SUCCESS_ACTION = createAction(actions.CREATE_DIVISION_SUCCESS);
const CREATE_DIVISION_ERROR_ACTION = createAction(actions.CREATE_DIVISION_ERROR);

//Listar Quizzes
const LIST_DIVISIONS_REQUESTED_ACTION = createAction(actions.LIST_DIVISIONS_REQUESTED);
const LIST_DIVISIONS_SUCCESS_ACTION = createAction(actions.LIST_DIVISIONS_SUCCESS);
const LIST_DIVISIONS_ERROR_ACTION = createAction(actions.LIST_DIVISIONS_ERROR);

//Obtener Quizz
const GET_DIVISION_REQUESTED_ACTION = createAction(actions.GET_DIVISION_REQUESTED);
const GET_DIVISION_SUCCESS_ACTION = createAction(actions.GET_DIVISION_SUCCESS);
const GET_DIVISION_ERROR_ACTION = createAction(actions.GET_DIVISION_ERROR);

//Actualizar
const UPDATE_DIVISION_REQUESTED_ACTION = createAction(actions.UPDATE_DIVISION_REQUESTED);
const UPDATE_DIVISION_SUCCESS_ACTION = createAction(actions.UPDATE_DIVISION_SUCCESS);
const UPDATE_DIVISION_ERROR_ACTION = createAction(actions.UPDATE_DIVISION_ERROR);

//eliminar
const DELETE_DIVISION_REQUESTED_ACTION = createAction(actions.DELETE_DIVISION_REQUESTED);
const DELETE_DIVISION_SUCCESS_ACTION = createAction(actions.DELETE_DIVISION_SUCCESS);
const DELETE_DIVISION_ERROR_ACTION = createAction(actions.DELETE_DIVISION_ERROR);

export {
    CREATE_DIVISION_REQUESTED_ACTION,
    CREATE_DIVISION_SUCCESS_ACTION,
    CREATE_DIVISION_ERROR_ACTION,

    LIST_DIVISIONS_REQUESTED_ACTION,
    LIST_DIVISIONS_SUCCESS_ACTION,
    LIST_DIVISIONS_ERROR_ACTION,

    GET_DIVISION_REQUESTED_ACTION,
    GET_DIVISION_SUCCESS_ACTION,
    GET_DIVISION_ERROR_ACTION,

    UPDATE_DIVISION_REQUESTED_ACTION,
    UPDATE_DIVISION_SUCCESS_ACTION,
    UPDATE_DIVISION_ERROR_ACTION,

    DELETE_DIVISION_REQUESTED_ACTION,
    DELETE_DIVISION_SUCCESS_ACTION,
    DELETE_DIVISION_ERROR_ACTION,


}